/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cleanzone.Vista;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author pedro
 */
public class GenerarReporte extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public GenerarReporte(String ubicacion, String codigoPostal, int contenedores, String incidencias, String estado, ImageIcon imagen) {
        initComponents();
        txtUbicacion.setText(ubicacion);
    txtCodigoPostal.setText(codigoPostal);
    spnContenedores.setValue(contenedores);
    txtIncidencias.setText(incidencias);
    CombEstadonEnvios.setSelectedItem(estado);
    lblImagen.setIcon(imagen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanelGenerarReporte = new javax.swing.JPanel();
        jLabelGenerarReporte = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtUbicacion = new javax.swing.JTextField();
        AgregarImagen = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EstadoEnvio = new javax.swing.JLabel();
        btnAgregarImagen = new javax.swing.JButton();
        txtCodigoPostal = new javax.swing.JTextField();
        CodigoPostal = new javax.swing.JLabel();
        spnContenedores = new javax.swing.JSpinner();
        ConLlenos = new javax.swing.JLabel();
        jScrollPaneIncidencias = new javax.swing.JScrollPane();
        txtIncidencias = new javax.swing.JTextArea();
        IncidenciasRepor = new javax.swing.JLabel();
        CombEstadonEnvios = new javax.swing.JComboBox<>();
        lblImagen = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(374, 673));
        setMinimumSize(new java.awt.Dimension(374, 673));
        setResizable(false);
        setSize(new java.awt.Dimension(374, 673));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelGenerarReporte.setMaximumSize(new java.awt.Dimension(374, 673));
        jPanelGenerarReporte.setMinimumSize(new java.awt.Dimension(374, 673));
        jPanelGenerarReporte.setOpaque(false);
        jPanelGenerarReporte.setPreferredSize(new java.awt.Dimension(374, 673));
        jPanelGenerarReporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGenerarReporte.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabelGenerarReporte.setText("Generar Reporte");
        jPanelGenerarReporte.add(jLabelGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 150, 30));

        btnCancelar.setBackground(java.awt.Color.orange);
        btnCancelar.setText("Inicio");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanelGenerarReporte.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 100, -1));

        btnGuardar.setBackground(java.awt.Color.orange);
        btnGuardar.setText("Siguiente");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanelGenerarReporte.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 110, 30));

        txtUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUbicacionActionPerformed(evt);
            }
        });
        jPanelGenerarReporte.add(txtUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 110, -1));

        AgregarImagen.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        AgregarImagen.setText("Agregar imagen");
        jPanelGenerarReporte.add(AgregarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("Ubicación del problema :");
        jPanelGenerarReporte.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        EstadoEnvio.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        EstadoEnvio.setText("Estado de Envío\t");
        jPanelGenerarReporte.add(EstadoEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        btnAgregarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarImagenActionPerformed(evt);
            }
        });
        jPanelGenerarReporte.add(btnAgregarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        txtCodigoPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoPostalActionPerformed(evt);
            }
        });
        jPanelGenerarReporte.add(txtCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 110, -1));

        CodigoPostal.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        CodigoPostal.setText("Codigo Postal :");
        jPanelGenerarReporte.add(CodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        spnContenedores.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        jPanelGenerarReporte.add(spnContenedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        ConLlenos.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ConLlenos.setText("Contenedores Llenos :\t");
        jPanelGenerarReporte.add(ConLlenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        txtIncidencias.setColumns(20);
        txtIncidencias.setRows(5);
        jScrollPaneIncidencias.setViewportView(txtIncidencias);

        jPanelGenerarReporte.add(jScrollPaneIncidencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 310, 80));

        IncidenciasRepor.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        IncidenciasRepor.setText("Incidencias Reportadas\t");
        jPanelGenerarReporte.add(IncidenciasRepor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        CombEstadonEnvios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enviado", "Pendiente", "Rechazado" }));
        CombEstadonEnvios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombEstadonEnviosActionPerformed(evt);
            }
        });
        jPanelGenerarReporte.add(CombEstadonEnvios, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 90, -1));

        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelGenerarReporte.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 170, 100));

        Fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\Fondo.jpeg")); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(373, 670));
        Fondo.setMinimumSize(new java.awt.Dimension(373, 670));
        Fondo.setPreferredSize(new java.awt.Dimension(373, 670));
        jPanelGenerarReporte.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        Fondo.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanelGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    VistaPreviaReporte ventanaVistaPreviaReporte = new VistaPreviaReporte(
    txtUbicacion.getText(), 
    txtCodigoPostal.getText(), 
    (Integer) spnContenedores.getValue(), 
    txtIncidencias.getText(), 
    CombEstadonEnvios.getSelectedItem().toString(), 
    (ImageIcon) lblImagen.getIcon()
);

// Mostrar la ventana antes de cerrar la actual
ventanaVistaPreviaReporte.setVisible(true);
this.dispose(); // Cierra la ventana actual después de abrir la vista previa

        
    this.dispose(); 
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Inicio ventanaInicio = new Inicio(); // Crea una nueva instancia de la ventana Inicio
    ventanaInicio.setVisible(true); // Muestra la ventana Inicio
    this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUbicacionActionPerformed

    private void CombEstadonEnviosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombEstadonEnviosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CombEstadonEnviosActionPerformed

    private void txtCodigoPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPostalActionPerformed

    private void btnAgregarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarImagenActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Seleccionar Imagen");
    
    // Filtro para permitir solo imágenes
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes", "jpg", "png", "jpeg"));

    // Mostrar el cuadro de diálogo para seleccionar archivos
    int seleccion = fileChooser.showOpenDialog(this);

    if (seleccion == JFileChooser.APPROVE_OPTION) {
        File archivoSeleccionado = fileChooser.getSelectedFile();
        String rutaImagen = archivoSeleccionado.getAbsolutePath();

        // Mostrar la imagen en un JLabel (ejemplo: lblImagen)
        ImageIcon icono = new ImageIcon(rutaImagen);
        Image imagen = icono.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH);
        lblImagen.setIcon(new ImageIcon(imagen));

        // Puedes guardar la ruta de la imagen en una variable si necesitas almacenarla
        System.out.println("Imagen seleccionada: " + rutaImagen);
    }
    }//GEN-LAST:event_btnAgregarImagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
        new GenerarReporte("Ubicación por defecto", "00000", 0, "Sin incidencias", "Desconocido", new ImageIcon()).setVisible(true);
    }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarImagen;
    private javax.swing.JLabel CodigoPostal;
    private javax.swing.JComboBox<String> CombEstadonEnvios;
    private javax.swing.JLabel ConLlenos;
    private javax.swing.JLabel EstadoEnvio;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel IncidenciasRepor;
    private javax.swing.JButton btnAgregarImagen;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelGenerarReporte;
    private javax.swing.JPanel jPanelGenerarReporte;
    private javax.swing.JScrollPane jScrollPaneIncidencias;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JSpinner spnContenedores;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextArea txtIncidencias;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
