/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cleanzone.Vista;

import javax.swing.ImageIcon;
import com.itextpdf.io.image.ImageData;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Image;
import com.mycompany.cleanzone.DAOFactory;
import com.mycompany.cleanzone.dao.ReporteDAO;
import com.mycompany.cleanzone.model.Reporte;
import java.awt.Component;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author pedro
 */
public class VistaPreviaReporte extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     * @param ubicacion
     * @param codigoPostal
     * @param contenedores
     * @param incidencias
     * @param estado
     * @param imagen
     */
    public VistaPreviaReporte(String ubicacion, String codigoPostal, int contenedores, String incidencias, String estado, ImageIcon imagen) {
        initComponents();
        
    lblUbicacion.setText(ubicacion);
    lblCodigoPostal.setText(codigoPostal);
    lblContenedores.setText(String.valueOf(contenedores));
    txtAreaIncidenRepor.setText(incidencias);
    lblEstadoEnvio.setText(estado);
    
    if (imagen != null) {
        lblImagen.setIcon(imagen);
    }
    }
    public VistaPreviaReporte() {
    // Puedes inicializar valores predeterminados si es necesario
    this("Ubicación por defecto", "00000", 0, "Sin incidencias", "Desconocido", new ImageIcon());
}
    private ImageIcon icono;  // Debe estar declarada en la clase
    private File imagenOriginal;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        JpanelVistPrevRE = new javax.swing.JPanel();
        jLabelVistaPrevRe = new javax.swing.JLabel();
        botonVoler = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        lblIncidenciasTitulo = new javax.swing.JLabel();
        lblEstadoEnvio = new javax.swing.JLabel();
        lblUbicacionTitulo1 = new javax.swing.JLabel();
        lblUbicacion = new javax.swing.JLabel();
        lblCodigoPostalTitulo1 = new javax.swing.JLabel();
        lblCodigoPostal = new javax.swing.JLabel();
        lblImagenIsertada = new javax.swing.JLabel();
        lblContenedoresTitulo2 = new javax.swing.JLabel();
        txtIncidencias = new javax.swing.JScrollPane();
        txtAreaIncidenRepor = new javax.swing.JTextArea();
        lblContenedores = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        lblEstadoEnvioTitulo1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(374, 673));
        setResizable(false);
        setSize(new java.awt.Dimension(374, 673));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JpanelVistPrevRE.setMaximumSize(new java.awt.Dimension(374, 673));
        JpanelVistPrevRE.setMinimumSize(new java.awt.Dimension(374, 673));
        JpanelVistPrevRE.setOpaque(false);
        JpanelVistPrevRE.setPreferredSize(new java.awt.Dimension(374, 673));
        JpanelVistPrevRE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelVistaPrevRe.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabelVistaPrevRe.setText("Vista Previa Reporte");
        JpanelVistPrevRE.add(jLabelVistaPrevRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 180, 30));

        botonVoler.setBackground(java.awt.Color.orange);
        botonVoler.setText("Editar");
        botonVoler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolerActionPerformed(evt);
            }
        });
        JpanelVistPrevRE.add(botonVoler, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 100, -1));

        btnConfirmar.setBackground(java.awt.Color.orange);
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        JpanelVistPrevRE.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, 120, 30));

        lblIncidenciasTitulo.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lblIncidenciasTitulo.setText("Incidencias Reportadas:");
        JpanelVistPrevRE.add(lblIncidenciasTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 160, 20));
        JpanelVistPrevRE.add(lblEstadoEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 160, 20));

        lblUbicacionTitulo1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lblUbicacionTitulo1.setText("Ubicación:");
        JpanelVistPrevRE.add(lblUbicacionTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 70, 20));
        JpanelVistPrevRE.add(lblUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 160, 20));

        lblCodigoPostalTitulo1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lblCodigoPostalTitulo1.setText("Codigo Postal :");
        JpanelVistPrevRE.add(lblCodigoPostalTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 120, 20));
        JpanelVistPrevRE.add(lblCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 160, 20));

        lblImagenIsertada.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lblImagenIsertada.setText("Imagen Isertada");
        JpanelVistPrevRE.add(lblImagenIsertada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 150, 20));

        lblContenedoresTitulo2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lblContenedoresTitulo2.setText("Contenedores Llenos :");
        JpanelVistPrevRE.add(lblContenedoresTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 150, 20));

        txtAreaIncidenRepor.setEditable(false);
        txtAreaIncidenRepor.setColumns(20);
        txtAreaIncidenRepor.setRows(5);
        txtIncidencias.setViewportView(txtAreaIncidenRepor);

        JpanelVistPrevRE.add(txtIncidencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 300, -1));
        JpanelVistPrevRE.add(lblContenedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 160, 20));

        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JpanelVistPrevRE.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 290, 90));

        lblEstadoEnvioTitulo1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lblEstadoEnvioTitulo1.setText("Estado de Envío:");
        JpanelVistPrevRE.add(lblEstadoEnvioTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 150, 20));

        Fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\Fondo.jpeg")); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(373, 670));
        Fondo.setMinimumSize(new java.awt.Dimension(373, 670));
        Fondo.setPreferredSize(new java.awt.Dimension(373, 670));
        JpanelVistPrevRE.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        Fondo.getAccessibleContext().setAccessibleName("");
        Fondo.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(JpanelVistPrevRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        BufferedImage imagenReporte = new BufferedImage(JpanelVistPrevRE.getWidth(), JpanelVistPrevRE.getHeight(), BufferedImage.TYPE_INT_ARGB);
    Graphics2D g2d = imagenReporte.createGraphics();
    JpanelVistPrevRE.paint(g2d);
    g2d.dispose();
    
    // 1️⃣ Obtener los datos ingresados en la interfaz
    String ubicacion = lblUbicacion.getText();
    int codigoPostal = Integer.parseInt(lblCodigoPostal.getText());
    int cantidadContenedoresLlenos = Integer.parseInt(lblContenedores.getText());
    String incidenciasReportadas = txtAreaIncidenRepor.getText();
    String estadoEnvio = lblEstadoEnvio.getText();
    java.util.Date fechaGeneracion = new java.util.Date(); // Fecha actual

    // 2️⃣ Crear el objeto Reporte
    Reporte reporte = new Reporte(
        0, 
        fechaGeneracion, 
        codigoPostal, 
        0.0, // Cantidad de residuos (ajústalo si lo necesitas)
        cantidadContenedoresLlenos, 
        incidenciasReportadas, 
        estadoEnvio
    );

    // 3️⃣ Guardar en la base de datos
    ReporteDAO reporteDAO = DAOFactory.getReporteDAO();
    boolean resultado = reporteDAO.insertarReporte(reporte);

    // 4️⃣ Mostrar mensaje
    if (resultado) {
        JOptionPane.showMessageDialog(this, "✅ Reporte enviado y guardado correctamente en la base de datos.");
    } else {
        JOptionPane.showMessageDialog(this, "❌ Error al guardar el reporte en la base de datos.");
    }

    // 5️⃣ Guardar la imagen del reporte
    try {
        File tempFile = new File("reporte_confirmado.png");
        ImageIO.write(imagenReporte, "png", tempFile);
        
        // Pasar a la siguiente interfaz ReporteConfirmado
        ReporteConfirmado reporteConfirmado = new ReporteConfirmado(tempFile);
        reporteConfirmado.setVisible(true);
        this.dispose();
    } catch (IOException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al guardar la imagen del reporte.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void botonVolerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolerActionPerformed
        // TODO add your handling code here:
    String ubicacion = lblUbicacion.getText();
    String codigoPostal = lblCodigoPostal.getText();
    int contenedores = Integer.parseInt(lblContenedores.getText());
    String incidencias = txtAreaIncidenRepor.getText();
    String estado = lblEstadoEnvio.getText();
    ImageIcon imagen = (ImageIcon) lblImagen.getIcon();
    this.dispose();

    // Abrir la ventana de "Generar Reporte" con los datos actuales
    GenerarReporte ventanaGenerarReporte = new GenerarReporte(ubicacion, codigoPostal, contenedores, incidencias, estado, imagen);
    ventanaGenerarReporte.setVisible(true);
    }//GEN-LAST:event_botonVolerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPreviaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPreviaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPreviaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPreviaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
         
          
            public void run() {
                new VistaPreviaReporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel JpanelVistPrevRE;
    private javax.swing.JButton botonVoler;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelVistaPrevRe;
    private javax.swing.JLabel lblCodigoPostal;
    private javax.swing.JLabel lblCodigoPostalTitulo1;
    private javax.swing.JLabel lblContenedores;
    private javax.swing.JLabel lblContenedoresTitulo2;
    private javax.swing.JLabel lblEstadoEnvio;
    private javax.swing.JLabel lblEstadoEnvioTitulo1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagenIsertada;
    private javax.swing.JLabel lblIncidenciasTitulo;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JLabel lblUbicacionTitulo1;
    private javax.swing.JTextArea txtAreaIncidenRepor;
    private javax.swing.JScrollPane txtIncidencias;
    // End of variables declaration//GEN-END:variables
}
